/**
 * @file theme_define.h
 * @author Forairaaaaa
 * @brief
 * @version 0.6
 * @date 2023-09-20
 *
 * @copyright Copyright (c) 2023
 *
 */
#pragma once

#include "ukr_fonts.hpp"

#define THEME_COLOR_BG (uint32_t)(0x333333)
#define THEME_COLOR_BG_DARK (uint32_t)(0x191919)
#define THEME_COLOR_SYSTEM_BAR (uint32_t)(0xD3D3D3) //(0x99FF00)
#define THEME_COLOR_SYSTEM_BAR_TEXT TFT_BLACK
#define THEME_COLOR_KB_BAR TFT_LIGHTGREY
#define THEME_COLOR_KB_BAR_ICON_BG TFT_DARKGREY
#define THEME_COLOR_KB_BAR_ICON_TEXT TFT_WHITE
#define THEME_COLOR_ICON (uint32_t)(0xE6E6E6)
#define THEME_COLOR_ICON_16 (uint16_t)(0x3CE7)
#define THEME_COLOR_BG_SELECTED (uint32_t)(0xD3D3D3)
#define THEME_COLOR_BG_SELECTED_DARK (uint32_t)(0xB2B2B2)
#define THEME_COLOR_SELECTED (uint32_t)(0x000000)
#define THEME_COLOR_RED (uint32_t)(0xFF0000)
#define THEME_COLOR_GREEN (uint32_t)(0x00FF00)
#define THEME_COLOR_YELLOW (uint32_t)(0xFFFF00)
#define THEME_COLOR_BLUE (uint32_t)(0x0000FF)
#define THEME_COLOR_MAGENTA (uint32_t)(0xFF00FF)
#define THEME_COLOR_CYAN (uint32_t)(0x00FFFF)
#define THEME_COLOR_ORANGE (uint32_t)(0xFFA500)
#define THEME_COLOR_PINK (uint32_t)(0xFFC0CB)
#define THEME_COLOR_DARKGREY (uint32_t)(0x808080)
#define THEME_COLOR_UNSELECTED (uint32_t)(0xFFFFFF)
#define THEME_COLOR_TRANSPARENT (uint32_t)(0x4CFF00)
#define THEME_COLOR_KEYBOARD_LOWER (uint32_t)(0xA0A0A0)
#define THEME_COLOR_KEYBOARD_UPPER (uint32_t)(0x0074FF)
#define THEME_COLOR_KEYBOARD_FN (uint32_t)(0xFF6A00)
#define THEME_COLOR_KEYBOARD_TEXT (uint32_t)(0x00FFFF)
#define ICON_WIDTH 48
#define ICON_GAP 20
#define ICON_MARGIN_TOP 20
#define ICON_TAG_MARGIN_TOP 5
#define ICON_SELECTED_WIDTH 64
#define FONT_HEIGHT 16
#define FONT_WIDTH 8

#define THEME_COLOR_KB_CAPS_LOCK TFT_SKYBLUE
#define THEME_COLOR_KB_ALT TFT_YELLOW
#define THEME_COLOR_KB_CTRL TFT_PINK
#define THEME_COLOR_KB_FN TFT_ORANGE
#define THEME_COLOR_KB_OPT TFT_DARKGREEN

#define THEME_COLOR_REPL_TEXT TFT_WHITE
#define FONT_10 &efontUK_10
#define FONT_12 &efontUK_12
#define FONT_14 &efontUK_14
#define FONT_16 &efontUK_16
